---
title: "ADHD and MCI cognitive functions in R"
output: pdf_document
---

Assessing cognitive and behavioral differences between older subjects with ADHD and MCI in R.

## Required packages

```{r}
require(readxl)
require(knitr)
require(dplyr)
require(ggplot2)
require(viridis)
```

## Data preprocessing

```{r}
adhd_df <- read_excel(path = "ADHD_MC.xlsx")
adhd_df
kable(adhd_df)
```

```{r}
#Missing values from the adhd_df
nrow(adhd_df)
sum(is.na(adhd_df))
last_cols <- adhd_df[c('cubost','TMTAz','TMTBz')]
colSums(is.na(last_cols))
```

```{r}
str(adhd_df)
```

There is one empty column in this dataset.

```{r}
clean_df <- adhd_df %>% select(-33)
clean_df
kable(clean_df)
```

## Data visualisation

```{r}
ggplot(clean_df, aes(x = factor(SEXO), fill = factor(SEXO))) +
  geom_bar() +
  labs(title = "Ratio between men and women", x = "Sex", y = "Number") +
  scale_x_discrete(labels = c("women", "men")) +
  scale_fill_viridis_d(option = "C") +
  theme_minimal() +
  geom_smooth () +
  theme(
    plot.title = element_text(hjust = 0.5),  
    panel.grid.major = element_blank(),      
    panel.grid.minor = element_blank()       
  )
```

```{r}
sex <- table(clean_df$SEXO)
women <- sex[1]/(sex[1]+sex[2])*100
men <- 100 - women
message <- sprintf("There were %.2f%% females.", women)
cat(message, "\n")
```

```{r}
ggplot(clean_df, aes(x = factor(DX), fill = factor(DX))) +
  geom_bar() +
  labs(title = "Ratio between clinical groups", x = "Clinical group", y = "Number") +
  scale_x_discrete(labels = c("control", "MCI", "ADHD")) +
  scale_fill_discrete(labels = c("control", "MCI", "ADHD")) +  
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),  
    panel.grid.major = element_blank(),      
    panel.grid.minor = element_blank()       
  )
```

```{r}
groups <- table(clean_df$DX)
control <- groups[1]/(groups[1]+groups[2]+groups[3])*100
mci <- groups[2]/(groups[1]+groups[2]+groups[3])*100
adhd <- 100 - (control+mci)

variables <- c("control", "mci", "adhd")
labels <- c("controls", "MSI patients", "ADHD patients")

for (i in seq_along(variables)) {
  message <- sprintf("There were %.2f%% %s.", get(variables[i]), labels[i])
  cat(message, "\n")
}
```

```{r}
clean_df %>%
  mutate (Anxiety = factor(Anxiety,
                      levels = c('0','1'),
                      labels = c('anxiety', 'no anxiety'))) %>%
  mutate (DX = factor(DX,
                      levels = c('0','1','2'),
                      labels = c('control', 'MSI','ADHD'))) %>%
  mutate (SEXO = factor(SEXO,
                      levels = c('0','1'),
                      labels = c('women', 'men'))) %>%
  ggplot(aes(IDADE, `MEEM total`))+
  labs(x = "Mental age", y = "Total MEEM")+
  geom_point(aes(color=DX), alpha = 0.5)+
  geom_smooth(method = 'lm')+
  facet_grid(SEXO~Anxiety)
```

```{r}
ggplot(clean_df, aes(x = factor(DX), y = Depression, fill = DX)) +
  geom_boxplot(alpha=0.5) +
  labs(x = "Clinical group", y = "Depression")+ 
  geom_point(aes(color=DX), alpha = 0.5)+
  geom_smooth()
```

```{r}
summary_depression <- aggregate(Depression ~ DX, data = clean_df, function(x) c(mean = mean(x), sd = sd(x)))
summary_depression2 <- do.call(data.frame, summary_depression)
summary_depression2
```

There is higher depression rate in ADHD patients, but the standard deviation values show that there is no statistical significance.

```{r}
clean_df %>%
  filter(cubos != '999') %>%                         #remove the outlier
  ggplot(aes(x = factor(DX), y = cubos, fill = DX)) +
  geom_boxplot(alpha=0.5) +
  labs(x = "Clinical group", y = "Cubos")+ 
  geom_point(aes(color=DX), alpha = 0.5)+
  geom_smooth()
```

```{r}
summary_anxiety <- aggregate(Anxiety ~ DX, data = clean_df, function(x) c(mean = mean(x), sd = sd(x)))
summary_anxiety2 <- do.call(data.frame, summary_anxiety)
summary_anxiety2
```

```{r}
ggplot(clean_df, aes(x = factor(DX), y = a1a5, fill = DX)) +
  geom_boxplot(alpha=0.5) +
  labs(x = "Clinical group", y = "a1a5")+ 
  geom_point(aes(color=DX), alpha = 0.5)+
  geom_smooth()

```
